[workspace]
members = [
  "crates/core",
  "crates/cli",
  "crates/plugins/js",
  "crates/plugins/css",
  "crates/plugins/html",
  "crates/plugins/glb"
]

resolver = "2"

[profile.dev]
opt-level = 1
lto = "thin"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.mini]
inherits = "release"
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.mini.package."*"]
opt-level = "z"
